
# Model Parameters
model_params: {
    model_config: {'name': 'GaussianLoDModel', 'kwargs': {'fork': 2, 'gs_attr': '3D', 'color_attr': 'RGB', 'feat_dim': 32, 'view_dim': 3, 'appearance_dim': 0, 'n_offsets': 10, 'voxel_size': 0.001, 'render_mode': 'RGB+ED', 'standard_dist': 34.41826629638671875, 'aerial_levels': 3, 'street_levels': 5}},
    pretrained_checkpoint: '',
    global_appearance: '',
    dataset_name: horizongs,
    scene_name: real/road/coarse,
    images: images,
    resolution: -1,
    white_background: False,
    random_background: False,
    resolution_scales: [1.0],
    data_device: cpu,
    eval: True,
    ratio: 1,
    data_format: colmap,
    add_mask: True,
    add_depth: True,
    add_aerial: True,
    add_street: True,
    llffhold: 32,
    source_path: "data/real/road"
}

# Pipeline Parameters
pipeline_params: {
    camera_balance: True,
    camera_proportion: 2-1,
    aerial_densify: True,
    street_densify: False,
    weed_ratio: 0.0,
    add_prefilter: True,
    vis_step: 5000,
    no_prefilter_step: 0
}

# Optimization Parameters
optim_params: {
    iterations: 60000,
    position_lr_init: 0.000000,
    position_lr_final: 0.000000,
    position_lr_delay_mult: 0.010000,
    position_lr_max_steps: 60000,
    offset_lr_init: 0.001000,
    offset_lr_final: 0.000010,
    offset_lr_delay_mult: 0.010000,
    offset_lr_max_steps: 60000,
    feature_lr: 0.007500,
    scaling_lr: 0.007000,
    rotation_lr: 0.002000,
    mlp_opacity_lr_init: 0.002000,
    mlp_opacity_lr_final: 0.000020,
    mlp_opacity_lr_delay_mult: 0.010000,
    mlp_opacity_lr_max_steps: 60000,
    mlp_cov_lr_init: 0.004000,
    mlp_cov_lr_final: 0.004000,
    mlp_cov_lr_delay_mult: 0.010000,
    mlp_cov_lr_max_steps: 60000,
    mlp_color_lr_init: 0.008000,
    mlp_color_lr_final: 0.000050,
    mlp_color_lr_delay_mult: 0.010000,
    mlp_color_lr_max_steps: 60000,
    appearance_lr_init: 0.000000,
    appearance_lr_final: 0.000000,
    appearance_lr_delay_mult: 0.010000,
    appearance_lr_max_steps: 60000,
    lambda_dssim: 0.200000,
    lambda_dreg: 0.010000,
    lambda_sky_opa: 0.050000,
    lambda_opacity_entropy: 0.050000,
    lambda_normal: 0.000000,
    normal_start_iter: 7000,
    lambda_dist: 0.000000,
    dist_start_iter: 3000,
    start_stat: 0,
    update_from: 500,
    update_interval: 300,
    update_until: 30000,
    overlap: False,
    densification: True,
    growing_type: max,
    pruning_type: mean,
    min_opacity: 0.005000,
    success_threshold: 0.800000,
    densify_grad_threshold: 0.015000,
    update_ratio: 0.200000,
    extra_ratio: 0.250000,
    extra_up: 0.050000,
    start_depth: 500,
    depth_l1_weight_init: 1.000000,
    depth_l1_weight_final: 0.010000
}
